import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/nav/navbar';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Donemo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />

      <main className={styles.main}>
        <h1 className={styles.title}>Donemo</h1>

        <p className={styles.description}>
          A curated art gallery - made with love by Donelia Morales.
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <img
              src='https://i.ibb.co/2PSn7JP/D81-DC3-E8-A7-CD-4-A0-E-809-F-A4-FA5-D1-AE857.jpg'
              height='300'
              width='300'
              style={{ borderRadius: '10px', transform: 'rotate(90deg)' }}
            />
          </a>

          <a className={styles.card}>
            <img
              src='https://i.ibb.co/F8VJ9Xg/ED230335-EBF4-4-CD6-A5-E8-0-E57842-F7968.jpg'
              height='300'
              width='300'
              style={{ borderRadius: '10px' }}
            />
          </a>

          <a className={styles.card}>
            <img
              src='https://i.ibb.co/r6fkx5H/7681559-B-49-F5-4-C4-D-A378-8-B62-D8541-B0-C.jpg'
              height='300'
              width='300'
              style={{ borderRadius: '10px', transform: 'rotate(180deg)' }}
            />
          </a>

          <a className={styles.card}>
            <img
              src='/placeholder.jpeg'
              height='100%'
              width='100%'
              style={{ borderRadius: '10px' }}
            />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a target='_blank' rel='noopener noreferrer'>
          by Maria Jose Ortiz
        </a>
      </footer>
    </div>
  );
}
