import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Donemo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Donemo</h1>

        <p className={styles.description}>
          A curated art gallery - made with ❤️ by Donelia Morales.
        </p>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <img
              src='/placeholder.jpeg'
              height='100%'
              width='100%'
              style={{ borderRadius: '10px' }}
            />
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <img
              src='/placeholder.jpeg'
              height='100%'
              width='100%'
              style={{ borderRadius: '10px' }}
            />
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}
          >
            <img
              src='/placeholder.jpeg'
              height='100%'
              width='100%'
              style={{ borderRadius: '10px' }}
            />
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <img
              src='/placeholder.jpeg'
              height='100%'
              width='100%'
              style={{ borderRadius: '10px' }}
            />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          by Maria Jose Ortiz
        </a>
      </footer>
    </div>
  );
}
